@startmindmap
'https://plantuml.com/mindmap-diagram


* 司机
    ** 登录注册
    *** 输入帐号信息
    *** 提交帐号信息

    ** 拼车
    *** 查看拼车订单
    *** 发起拼车
    *** 接受订单

    ** 订单
    *** 查看所有订单
    *** 修改订单状态
    *** 评价订单
    *** 查看订单评价
*** 对订单发起投诉

    ** 聊天
    *** 查看聊天室列表
    *** 查看聊天室信息记录
    *** 发送信息

    ** 我的
    *** 查看个人信息
    *** 修改个人信息
    *** 注册乘客身份
@endmindmap
