@startuml
'https://plantuml.com/activity-diagram-beta
skinparam ArrowHeadColor none
:基于JAVA的湛江网络车系统;
split
:无帐号用户;
:登录注册;
split again
:管理员;
    split
    :登录注册;
    split again
    :车票管理;
    split again
    :乘客管理;

    split again
    :司机管理;

    split again
    :帐号管理;

    split again
    :车票管理;

    split again
    :投诉管理;

    end split
split again
:司机;
split again
:乘客;
end split


@enduml
