@startmindmap
'https://plantuml.com/mindmap-diagram


 * 管理员

 ** 登录
 *** 输入帐号
 *** 提交帐号

 ** 车票管理
 *** 查看车票
 *** 新加车票
 *** 删除车票
 *** 修改车票

 ** 乘客管理
 *** 查看乘客
 *** 删除乘客

 ** 司机管理
 *** 查看司机
 *** 查看司机驾驶证
 *** 删除司机

 ** 帐号管理
 *** 查看帐号
 *** 删除帐号
 *** 修改帐号密码


 ** 投诉管理
 *** 查看投诉用户
 *** 查看与用户沟通记录
 *** 发送信息

@endmindmap
