@startuml
'https://plantuml.com/sequence-diagram

autonumber
'autoactivate on
actor passenger
participant ticket


passenger -> ticket :查询票
activate passenger
activate ticket

passenger <- ticket: 返回票的信息

'passenger -> ticket: 选择购买的票

passenger -> passenger: 选择要购买的票

create order
passenger -> order: 提交要购买的票
activate order
order -> ticket: 票的数量减少
deactivate ticket

order -> order: 生成乘客购票订单

passenger -> order: 乘客查看订单
order -> passenger: 返回乘客订单
passenger -> order: 乘客支付订单

order -> order: 修改订单状态

order -> passenger: 购票成功

deactivate order
deactivate passenger

@enduml