@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

actor passenger
participant 乘客界面
entity order
control 程序逻辑层
database 程序数据库

passenger -> 乘客界面: 点击发出拼车
乘客界面 --> 乘客界面: 返回订单输入框
passenger --> 乘客界面: 输入拼车订单的信息
乘客界面 -> order: 根据信息创建订单
order -> 程序逻辑层: 提交订单
程序逻辑层 -> 程序数据库: 保存订单
程序逻辑层 --> order: 返回成功结果

order -> order: 根据结果创建订单

order --> 乘客界面: 返回根据结果创建的订单
deactivate order
deactivate 程序数据库


@enduml