@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor driver
participant 拼车界面
control 程序逻辑层
database 程序数据库


driver -> 拼车界面: 进入拼车界面
activate 拼车界面

拼车界面 -> 程序逻辑层: 查询所有的拼车订单
activate 程序逻辑层

程序逻辑层 -> 程序数据库: 查询所有的拼车订单
deactivate 程序逻辑层
activate 程序数据库

程序数据库 --> 程序逻辑层 : 返回所有的拼车订单
deactivate 程序数据库
activate 程序逻辑层
程序逻辑层 --> 拼车界面 : 返回所有的拼车订单
deactivate 程序逻辑层
拼车界面 -> driver: 显示拼车订单

driver -> 拼车界面: 点击接取订单

拼车界面 -> 程序逻辑层: 提交订单
activate 程序逻辑层
程序逻辑层 -> 程序逻辑层: 修改订单信息
程序逻辑层 -> 程序数据库: 保存订单
程序逻辑层 -> 拼车界面: 返回接取订单结果
拼车界面 -> driver: 返回接取订单结果


deactivate 拼车界面
deactivate 程序逻辑层
deactivate 程序数据库

@enduml