# 数据库配置信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinecarhailing
    username: onlinecarhailing
    password: 123456
  redis:
    host: localhost
    port: 6379

# mybatis的配置
mybatis:
  configuration:
    # 开启mybatis驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 打开mybatis的提示
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springboot内置的tomcat的配置。
server:
  #springboot内置的tomcat占用的端口号
  port: 8085
# Spring Boot应用程序中集成Spring Boot Actuator模块，以便提供对应用程序的监控和管理功能。
# Spring Boot Actuator是一个用于公开各种信息的端点（endpoints）的库，这些端点可以让你了解和管理你的应用程序。
management:
  endpoints:
    web:
      exposure:
        include: env,info,health


