@startuml
'https://plantuml.com/use-case-diagram

left to right direction

'
'(车票)<|-- (显示所有车票)
'(车票)<|--(购票)
'
'
'(拼车)<|-- (发起拼车)
'(拼车)<|--(接受订单)
'
'
'(订单) <|-- (取消订单)
'(订单) <|-- (发送信息)
'(订单) <|-- (投诉)
'
'(聊天) <|-- (查看信息)
'(聊天) <|-- (选择聊天室)
'(聊天) <|-- (发送信息)
'
'(我的)<|-- (修改个人信息)
'(我的)<|-- (注册司机身份)

'
':乘客: --> (车票)
':乘客: --> (拼车)
':乘客: --> (订单)
':乘客: --> (聊天)
':乘客: --> (我的)

:乘客: -up-> (查看所有车票)
:乘客: -up-> (购票)

:乘客: -up-> (发起拼车)
:乘客: -up-> (接受订单)

':乘客: -up-> (取消订单)
':乘客: -right-> (发送信息)
':乘客: -right-> (投诉)
:乘客: -right-> (订单管理)


:乘客: -right-> (登录注册)

':乘客: --> (查看信息)
':乘客: --> (选择聊天室)
':乘客: --> (发送信息)
:乘客: --> (用户交流)


:乘客: --> (修改个人信息)
:乘客: --> (注册司机身份)

@enduml