@startuml
'https://plantuml.com/use-case-diagram

left to right direction

'(拼车)<|-- (发起拼车)
'(拼车)<|--(接受订单)
'
'
'(订单) <|-- (取消订单)
'(订单) <|-- (发送信息)
'(订单) <|-- (投诉)
'
'(聊天) <|-- (查看信息)
'(聊天) <|-- (选择聊天室)
'(聊天) <|-- (发送信息)
'
'(我的)<|-- (修改个人信息)
'(我的)<|-- (选择为这个帐号注册乘客身份)


':司机: --> (拼车)
':司机: --> (订单)
':司机: --> (聊天)
':司机: --> (我的)

:司机: -up-> (发起拼车)
:司机: -up-> (接受订单)

':司机: -up-> (取消订单)
':司机: -up-> (发送信息)
':司机: --> (投诉)

:司机: -up-> (订单管理)

:司机: -right-> (登录注册)

':司机: --> (查看信息)
':司机: --> (选择聊天室)
':司机: --> (发送信息)
:司机: --> (用户交流)

:司机: --> (修改个人信息)
:司机: --> (注册乘客身份)

@enduml