@startuml
'https://plantuml.com/use-case-diagram

left to right direction
'
'(车票管理)<|-- (修改车票)
'(车票管理)<|--(添加车票)
'(车票管理)<|--(批量删除车票)
'
'(乘客管理) <|-- (批量删除乘客)
'
'(司机管理) <|-- (批量删除司机)
'(司机管理) <|-- (查看驾驶证)
'
'(帐号管理)<|-- (批量删除帐号)
'(帐号管理)<|-- (修改密码)
'
'(车辆管理) <|-- (添加车辆)
'(车辆管理) <|-- (批量删除车辆)
'(车辆管理) <|-- (编辑车票)
'
'
'(投诉管理) <|-- (查看投诉)
'(投诉管理) <|-- (与用户交流)

':管理员: -left-> (查看所有车票)
':管理员: -up-> (修改车票)
':管理员: -up-> (添加车票)
':管理员: -up-> (批量删除车票)

:管理员: -up-> (车票管理)

:管理员: -left-> (批量删除乘客)

':管理员: -right-> (批量删除司机)
':管理员: -right-> (查看驾驶证)
:管理员: -right-> (司机管理)

':管理员: -down-> (批量删除帐号)
':管理员: -down-> (修改密码)
:管理员: -down-> (帐号管理)

':管理员: -up-> (添加车辆)
':管理员: -up-> (批量删除车辆)
:管理员: -up-> (车辆管理)


':管理员: --> (查看投诉)
':管理员: --> (与用户交流)
:管理员: --> (用户交流)

:管理员: -left-> (登录)

@enduml