@startuml
'https://plantuml.com/activity-diagram-beta

start
:点击某一订单的接取订单;
if (订单有足够的空位？) then(有)

:修改司机发出的拼车订单;

fork

if (司机发出的拼车订单的空位为0？) then (不为0)
:订单仍旧显示在乘客的拼车界面上;
else (为0)
:订单不再显示在乘客的拼车界面上;
endif
fork again
:为司机生成乘客接取拼车订单而生成的订单;
:为乘客生成乘客接取司机发出的拼车订单的订单;
end fork
stop
else (没有)
:提示用户空位不足;

stop

@enduml
