@startuml
'https://plantuml.com/activity-diagram-beta

start

:选择功能;

split
:拼车;
    split
    :发起拼车;
    split again
    :接受订单;
    end split;
split again
:订单;
    split
    :取消订单;
    split again
    :发送信息;
    split again
    :投诉;
    end split;
split again
:聊天;
:选择聊天对象;
:得到所有信息记录;
    fork
    :查看信息;
    fork again
    :发送信息;
    end fork
split again
:我的;
 split
 :修改个人信息;
 split again
 :选择为这个帐号注册乘客身份;
 end split;
end split

stop


@enduml
