@startuml
'https://plantuml.com/activity-diagram-beta

start

:点击添加车票，唤出要增加的票的信息;
:输入要增加的票的信息;
:点击确定;
if (新增的票的信息合法？) then(合法)
:提交到服务器保存起来;
else (不合法)
:提示用户;
stop
endif
:页面刷新;
:页面显示所有的车票，包括刚刚添加的;
stop

@enduml
