@startuml
'https://plantuml.com/activity-diagram-beta

start

:选择功能;
split
:车票管理;
    split
:添加;

    split again
:批量删除;

    split again
:编辑;
    end split;
split again
:乘客管理;

:批量删除;

split again
:司机管理;
:批量删除;

split again
:帐号管理;
    split
    :批量删除;
    split again
    :修改密码;
    end split;
split again
:车票管理;
    split
    :添加;
    split again
    :批量删除;
    split again
    :编辑;
    end split;
split again
:投诉管理;
:选择用户;
end split

stop





@enduml
